### ISSUE TITLE
Windows docker run .bat script

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/dockerfiles#39]
**Description:**
- Add instructions for running a centos/ubuntu docker container from a windows environment.
- Add a .bat script (similar to `mantid_development.sh`) that will run the docker container from a windows environment. The current shell script doesn't work on windows.

**Comment by martyngigg** [comment]
As the PR suggests [WSL2](https://developer.mantidproject.org/WindowsSubsystemForLinux.html#windowssubsystemforlinux) was a better way forward.
