### ISSUE TITLE
Upgrade macOS builders to at least Big Sur (v11)

### ISSUE THREAD

**Issue by ConorMFinn** [mantidproject/dockerfiles#73]
~~Both the current running mac builders are on High Sierra (10.13). This hasn't been getting security updates since november 2020. We should be on at least Big Sur, which is still getting updates. We should avoid upgrading to ventura though, since there's been some issues with JAMF and the network at RAL.~~

The current running builders don't support anything higher than high-sierra, they're too old. 
We need some way of building both an ARM and an x86 version of Mantid on an ARM machine.

**Comment by sf1919** [comment]
2 new Macs accquired.
