### ISSUE TITLE
Cleanup Linux docker images

### ISSUE THREAD

**Issue by sf1919** [mantidproject/dockerfiles#77]
The mantid-development docker image for Linux setup (https://github.com/mantidproject/dockerfiles/blob/main/Linux/development/docker/CentOS7Slim.Dockerfile) could do with some tidying up. 

In particular 
- do we still need to install ccache?
- Do we still need cppcheck part included?

Also the setting of the latex paths seems to be in both the dockerfile and the latex shell file. Is this necessary?

**Comment by SilkeSchomann** [comment]
Regarding the setting of latex paths: First of all we need to replace '2022' with '2023'. The paths have to be set in the dockerfile as otherwise the installation of the anyfontsize package does not work. We could remove them in the latex shell file though.
