### ISSUE TITLE
Give isiscloudwin4 more disk space

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/dockerfiles#79]
I think there is only 80GB available to this node. Also investigate whether isicloudwin3 needs upgrading.

**Comment by robertapplin** [comment]
Just checked, and `isiscloudwin3` has 500GB, so thats all good and doesn't need upgrading

**Comment by MialLewis** [comment]
This is an error in set up of the VM by infrastructure, I've contacted them to increase the storage.
